# Config for creating a housing dataset

[tier-1]
price.range = "100000-200000"
bedrooms.range = "1-3"
bathrooms.range = "1-3"
council_tax.list = ["A", "B", "C"]
freehold.list = [true, false]
garage.list = [false]
parking.list = [true, false]

[tier-2]
price.range = "200000-300000"
bedrooms.range = "2-4"
bathrooms.range = "2-4"
council_tax.list = ["B", "C", "D"]
freehold.list = [true, false]
garage.list = [true, false]
parking.list = [true, false]

[tier-3]
price.range = "300000-400000"
bedrooms.range = "3-5"
bathrooms.range = "3-5"
council_tax.list = ["D", "E", "F"]
freehold.list = [true]
garage.list = [true, false]
parking.list = [true, false]

[tier-4]
price.range = "400000-1000000"
bedrooms.range = "3-8"
bathrooms.range = "3-8"
council_tax.list = ["D", "E", "F"]
freehold.list = [true]
garage.list = [true, false]
parking.list = [true]