# Config for creating a housing dataset

[tier-1]
price = "100000-200000"
bedrooms = "1-3"
bathrooms = "1-3"
estate_agent_code = "1-5" 
transport_link_code = "1-8"
council_tax = ["A", "B", "C"]
freehold = [true, false]
garage = [false]
parking = [true, false]


[tier-2]
price = "200000-300000"
bedrooms = "2-4"
bathrooms = "2-4"
estate_agent_code = "2-5" 
transport_link_code = "2-8"
council_tax = ["B", "C", "D"]
freehold = [true, false]
garage = [true, false]
parking = [true, false]

[tier-3]
price = "300000-400000"
bedrooms = "3-5"
bathrooms = "3-5"
estate_agent_code = "3-5" 
transport_link_code = "3-8"
council_tax = ["D", "E", "F"]
freehold = [true]
garage = [true, false]
parking = [true, false]

[tier-4]
price = "400000-1000000"
bedrooms = "3-8"
bathrooms = "3-8"
estate_agent_code = "3-5" 
transport_link_code = "3-8"
council_tax = ["D", "E", "F"]
freehold = [true]
garage = [true, false]
parking = [true]